#!/usr/bin/env bash
# Configures web server web-02

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i '11i\add_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
sudo service nginx start
