#!/usr/bin/env bash
# displays a 'To infinity and beyond' indefinitely
#+ with a 'sleep 2' between iteration
# displays 'I am invincible !!!' when receiving
#+ SIGTERM

while true
do
    echo 'To infinity and beyond'
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
