#!/usr/bin/env bash
# Displays 'Best School' 10 times but 'Hi' on after the
#+ 9th iteration

i=0

while (($i <= 10));

    do
        if (($i = 8));
            echo Best School
            echo Hi
        do
        echo Best School
    ((i++))
done
