#!/usr/bin/env bash
# Displays 'Best School' 10 times, but for the 9th iteration,
#+ displays 'Best School' and then 'Hi' on a new line
#+ using while-loop and if statement

i=0
while (($i <= 10));
	do
		if (($i = 8));
			echo 'Best School'
            echo 'Hi'
        do
		echo 'Best School'
	((i++))
done
