#!/usr/bin/env bash
# Loops from 1 to 10 and:
#+ displays bad luck for the 4th loop iteration,
#+ displays good luck for the 8th loop iteration,
#+ displays Best School for the other iterations,


i=0
while((i < 10));
	do
		if i = 3
			echo bad luck

		elif i = 7
			do
			echo good luck
		else
			do
			echo Best School
	((i++))
done
